### ISSUE TITLE
loading png graph reported an error of missing InputMarker node

### ISSUE THREAD

**Issue by D-Mad** [Lightricks/LongAnimateDiff#1]
![image](https://github.com/Lightricks/LongAnimateDiff/assets/8207507/0ffb5c31-91b9-40a2-aef6-a224a216e3db)
I loaded your graph png but it gives me a node error and I can't find the missing node, How to fix it ?

**Comment by Naomi-Ken-Korem** [comment]
[vid2vidLongAnimateDiff.json](https://github.com/Lightricks/LongAnimateDiff/files/13742313/vid2vidLongAnimateDiff.json)
Here is a json that should work, try it out instead ( I removed the undefined nodes)
